# User config
author: "Sarah Hale"
tagline: "Portfolio"
description: "A developer and UX designer from Sweden! I think of life as a kind of computer game, where you can level up your skills and get out of your comfort zone whilst having fun along the way! :muscle::tada:"
keywords: "UX, developer"
email: "sarahhale95@gmail.com"
linkedin: "https://www.linkedin.com/in/sarah-hale-365a7113b/"
resume: "https://drive.google.com/file/d/1IwnZZeC5iLKoT90ljp-PFcuM9uMRXFlK/view"
github: "https://github.com/sarahmhale"

# Site config
plugins:
  - jemoji
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
